### ISSUE TITLE
拜托！

### ISSUE THREAD

**Issue by KkltSwk** [HenryVarro666/Movie-Recommendation-System#2]
为什么pycharm打开后无法在pycharm上运行，但是在terminial就可以。就是在pycharm上死活安装不上django。

**Comment by HenryVarro666** [comment]
你这个提问有点抽象，不是很懂你都有啥步骤可能存在问题，错误的提示是啥。我盲猜大概率要么是interpreter要么是packages要么是venv出了问题。我录屏尝试解决你这个问题，用了一个笨方法：手动安装包。你看一下能否解决你的问题呢？
