### ISSUE TITLE
视频不能播放

### ISSUE THREAD

**Issue by happylee** [HenryVarro666/Movie-Recommendation-System#3]
你好，我下载的视频文件不能播放，能再上传一次吗？谢谢了

**Comment by HenryVarro666** [comment]
你好。我刚刚试着clone了一下，三个MP4文件都是可以播放的。你可以重新下载或者换个播放器试试

**Comment by happylee** [comment]
嗯，我刚才压缩包下载的，播放不了，换个方式下载成功了，谢谢了
